create table if not exists formularios_campo
(
    id_campo     uuid         not null
        primary key,
    tipo         varchar(20)  not null,
    clase        varchar(30)  not null,
    nombre_campo varchar(64)  not null,
    etiqueta     varchar(100) not null,
    ayuda        varchar(255),
    config       text,
    requerido    boolean
);

alter table formularios_campo
    owner to santa_ana;

create table if not exists formularios_categoria
(
    id          uuid         not null
        primary key,
    nombre      varchar(100) not null,
    descripcion text         not null
);

alter table formularios_categoria
    owner to santa_ana;

create table if not exists formularios_clase_campo
(
    clase      varchar(30) not null
        primary key,
    estructura text
);

alter table formularios_clase_campo
    owner to santa_ana;

create index if not exists formularios_clase_campo_clase_583268a3_like
    on formularios_clase_campo (clase varchar_pattern_ops);

create table if not exists formularios_usuario
(
    last_login     timestamp with time zone,
    nombre_usuario varchar(50)  not null
        primary key,
    nombre         varchar(100) not null,
    correo         varchar(254) not null
        unique,
    password       varchar(128) not null,
    activo         boolean      not null,
    acceso_web     boolean      not null,
    is_staff       boolean      not null,
    is_superuser   boolean      not null
);

alter table formularios_usuario
    owner to santa_ana;

create index if not exists formularios_usuario_nombre_usuario_f9b1e930_like
    on formularios_usuario (nombre_usuario varchar_pattern_ops);

create index if not exists formularios_usuario_correo_8ac38a5b_like
    on formularios_usuario (correo varchar_pattern_ops);

create table if not exists formularios_usuario_groups
(
    id         bigint generated by default as identity
        primary key,
    usuario_id varchar(50) not null
        constraint formularios_usuario__usuario_id_dc265385_fk_formulari
            references formularios_usuario
            deferrable initially deferred,
    group_id   integer     not null
        constraint formularios_usuario_groups_group_id_59261c95_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    constraint formularios_usuario_groups_usuario_id_group_id_9443b0e1_uniq
        unique (usuario_id, group_id)
);

alter table formularios_usuario_groups
    owner to santa_ana;

create index if not exists formularios_usuario_groups_usuario_id_dc265385
    on formularios_usuario_groups (usuario_id);

create index if not exists formularios_usuario_groups_usuario_id_dc265385_like
    on formularios_usuario_groups (usuario_id varchar_pattern_ops);

create index if not exists formularios_usuario_groups_group_id_59261c95
    on formularios_usuario_groups (group_id);

create table if not exists formularios_usuario_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    usuario_id    varchar(50) not null
        constraint formularios_usuario__usuario_id_f63bbbfb_fk_formulari
            references formularios_usuario
            deferrable initially deferred,
    permission_id integer     not null
        constraint formularios_usuario__permission_id_cb4c324e_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint formularios_usuario_user_usuario_id_permission_id_1403bb32_uniq
        unique (usuario_id, permission_id)
);

alter table formularios_usuario_user_permissions
    owner to santa_ana;

create index if not exists formularios_usuario_user_permissions_usuario_id_f63bbbfb
    on formularios_usuario_user_permissions (usuario_id);

create index if not exists formularios_usuario_user_permissions_usuario_id_f63bbbfb_like
    on formularios_usuario_user_permissions (usuario_id varchar_pattern_ops);

create index if not exists formularios_usuario_user_permissions_permission_id_cb4c324e
    on formularios_usuario_user_permissions (permission_id);

create table if not exists formularios_formulario
(
    id                     uuid         not null
        primary key,
    nombre                 varchar(100) not null,
    descripcion            text         not null,
    permitir_fotos         boolean      not null,
    permitir_gps           boolean      not null,
    disponible_desde_fecha date         not null,
    disponible_hasta_fecha date         not null,
    estado                 varchar(20)  not null,
    forma_envio            varchar(30)  not null,
    es_publico             boolean      not null,
    auto_envio             boolean      not null,
    categoria_id           uuid
        constraint formularios_formular_categoria_id_01bd3ee9_fk_formulari
            references formularios_categoria
            deferrable initially deferred,
    periodicidad           integer
);

alter table formularios_formulario
    owner to santa_ana;

create index if not exists formularios_formulario_categoria_id_01bd3ee9
    on formularios_formulario (categoria_id);

create table if not exists formularios_formularioindexversion
(
    id_index_version uuid                     not null
        primary key,
    fecha_creacion   timestamp with time zone not null
);

alter table formularios_formularioindexversion
    owner to santa_ana;

create table if not exists formularios_fuente_datos
(
    id             uuid                     not null
        primary key,
    nombre         varchar(200)             not null,
    descripcion    text                     not null,
    archivo_nombre varchar(255)             not null,
    blob_name      varchar(500)             not null,
    blob_url       varchar(1000)            not null,
    tipo_archivo   varchar(10)              not null,
    columnas       jsonb                    not null,
    preview_data   jsonb                    not null,
    fecha_subida   timestamp with time zone not null,
    activo         boolean                  not null,
    creado_por_id  varchar(50)
        constraint formularios_fuente_d_creado_por_id_d51268af_fk_formulari
            references formularios_usuario
            deferrable initially deferred
);

alter table formularios_fuente_datos
    owner to santa_ana;

create index if not exists formularios_fuente_datos_creado_por_id_d51268af
    on formularios_fuente_datos (creado_por_id);

create index if not exists formularios_fuente_datos_creado_por_id_d51268af_like
    on formularios_fuente_datos (creado_por_id varchar_pattern_ops);

create table if not exists formularios_grupo
(
    id_grupo       uuid         not null
        primary key,
    nombre         varchar(150) not null,
    id_campo_group uuid         not null
        unique
        constraint formularios_grupo_id_campo_group_fba9dbb9_fk_formulari
            references formularios_campo
            deferrable initially deferred
);

alter table formularios_grupo
    owner to santa_ana;

create table if not exists formularios_pagina
(
    id_pagina   uuid         not null
        primary key,
    secuencia   integer      not null
        constraint formularios_pagina_secuencia_check
            check (secuencia >= 0),
    nombre      varchar(120) not null,
    descripcion text         not null
);

alter table formularios_pagina
    owner to santa_ana;

create table if not exists formularios_pagina_version
(
    id_pagina_version varchar(32)              not null
        primary key,
    fecha_creacion    timestamp with time zone not null,
    id_pagina         uuid
        constraint formularios_pagina_v_id_pagina_13267a50_fk_formulari
            references formularios_pagina
            deferrable initially deferred
);

alter table formularios_pagina_version
    owner to santa_ana;

create index if not exists formularios_pagina_version_id_pagina_version_078312aa_like
    on formularios_pagina_version (id_pagina_version varchar_pattern_ops);

create index if not exists formularios_pagina_version_id_pagina_13267a50
    on formularios_pagina_version (id_pagina);

create index if not exists formularios_id_pagi_78e8b2_idx
    on formularios_pagina_version (id_pagina asc, fecha_creacion desc);

create table if not exists formularios_formularios_index_version
(
    id_index_version uuid not null
        primary key
        constraint formularios_formular_id_index_version_e3b321ce_fk_formulari
            references formularios_formularioindexversion
            deferrable initially deferred,
    id_formulario    uuid not null
        constraint formularios_formular_id_formulario_d0a77691_fk_formulari
            references formularios_formulario
            deferrable initially deferred
);

alter table formularios_formularios_index_version
    owner to santa_ana;

create index if not exists formularios_formularios_index_version_id_formulario_d0a77691
    on formularios_formularios_index_version (id_formulario);

create table if not exists formularios_fuente_datos_valor
(
    id         uuid                     not null
        primary key,
    columna    varchar(200)             not null,
    key_text   text,
    label_text text                     not null,
    valor_raw  jsonb                    not null,
    extras     jsonb                    not null,
    creado_en  timestamp with time zone not null,
    campo_id   uuid                     not null
        constraint formularios_fuente_d_campo_id_845763f2_fk_formulari
            references formularios_campo
            deferrable initially deferred,
    fuente_id  uuid                     not null
        constraint formularios_fuente_d_fuente_id_d2de8f3f_fk_formulari
            references formularios_fuente_datos
            deferrable initially deferred,
    constraint formularios_fuente_datos_valor_campo_id_key_text_8e0934f7_uniq
        unique (campo_id, key_text)
);

alter table formularios_fuente_datos_valor
    owner to santa_ana;

create index if not exists formularios_fuente_datos_valor_campo_id_845763f2
    on formularios_fuente_datos_valor (campo_id);

create index if not exists formularios_fuente_datos_valor_fuente_id_d2de8f3f
    on formularios_fuente_datos_valor (fuente_id);

create index if not exists formularios_campo_i_254189_idx
    on formularios_fuente_datos_valor (campo_id, label_text);

create index if not exists formularios_campo_i_4d9317_idx
    on formularios_fuente_datos_valor (campo_id, key_text);

create table if not exists formularios_campo_grupo
(
    id       bigint generated by default as identity
        primary key,
    id_campo uuid not null
        constraint formularios_campo_gr_id_campo_13b94d4f_fk_formulari
            references formularios_campo
            deferrable initially deferred,
    id_grupo uuid not null
        constraint formularios_campo_gr_id_grupo_964ab96e_fk_formulari
            references formularios_grupo
            deferrable initially deferred,
    constraint formularios_campo_grupo_id_grupo_id_campo_3f10fa8b_uniq
        unique (id_grupo, id_campo)
);

alter table formularios_campo_grupo
    owner to santa_ana;

create index if not exists formularios_campo_grupo_id_campo_13b94d4f
    on formularios_campo_grupo (id_campo);

create index if not exists formularios_campo_grupo_id_grupo_964ab96e
    on formularios_campo_grupo (id_grupo);

create trigger trg_acg_row_audit
    after insert or update or delete
    on formularios_campo_grupo
    for each row
execute procedure audit.fn_row_log();

create trigger trg_acg_truncate_audit
    after truncate
    on formularios_campo_grupo
execute procedure audit.fn_truncate_log();

create table if not exists formularios_pagina_index_version
(
    id_pagina        uuid not null
        primary key
        constraint formularios_pagina_i_id_pagina_2cbac61f_fk_formulari
            references formularios_pagina
            deferrable initially deferred,
    id_index_version uuid not null
        constraint formularios_pagina_i_id_index_version_4bafe97f_fk_formulari
            references formularios_formularioindexversion
            deferrable initially deferred
);

alter table formularios_pagina_index_version
    owner to santa_ana;

create index if not exists formularios_pagina_index_version_id_index_version_4bafe97f
    on formularios_pagina_index_version (id_index_version);

create table if not exists formularios_user_formulario
(
    id               bigint generated by default as identity
        primary key,
    id_formulario_id uuid        not null
        constraint formularios_user_for_id_formulario_id_625621e0_fk_formulari
            references formularios_formulario
            deferrable initially deferred,
    id_usuario_id    varchar(50) not null
        constraint formularios_user_for_id_usuario_id_3f549cb5_fk_formulari
            references formularios_usuario
            deferrable initially deferred,
    constraint formularios_user_formula_id_formulario_id_id_usua_75d33c88_uniq
        unique (id_formulario_id, id_usuario_id)
);

alter table formularios_user_formulario
    owner to santa_ana;

create index if not exists formularios_user_formulario_id_formulario_id_625621e0
    on formularios_user_formulario (id_formulario_id);

create index if not exists formularios_user_formulario_id_usuario_id_3f549cb5
    on formularios_user_formulario (id_usuario_id);

create index if not exists formularios_user_formulario_id_usuario_id_3f549cb5_like
    on formularios_user_formulario (id_usuario_id varchar_pattern_ops);

create index if not exists formularios_id_usua_73941f_idx
    on formularios_user_formulario (id_usuario_id, id_formulario_id);

create table if not exists formularios_pagina_campo
(
    id_campo          uuid        not null
        primary key
        constraint formularios_pagina_c_id_campo_32cb62da_fk_formulari
            references formularios_campo
            deferrable initially deferred,
    sequence          integer
        constraint formularios_pagina_campo_sequence_check
            check (sequence >= 0),
    id_pagina_version varchar(32) not null
        constraint formularios_pagina_c_id_pagina_version_dbea0a3d_fk_formulari
            references formularios_pagina_version
            deferrable initially deferred,
    constraint formularios_pagina_campo_id_campo_id_pagina_versi_bad4d405_uniq
        unique (id_campo, id_pagina_version)
);

alter table formularios_pagina_campo
    owner to santa_ana;

create index if not exists formularios_pagina_campo_id_pagina_version_dbea0a3d
    on formularios_pagina_campo (id_pagina_version);

create index if not exists formularios_pagina_campo_id_pagina_version_dbea0a3d_like
    on formularios_pagina_campo (id_pagina_version varchar_pattern_ops);

create table if not exists formularios_entry
(
    id               uuid                     default gen_random_uuid()       not null
        primary key,
    id_usuario_id    text                                                     not null
        references formularios_usuario,
    form_id          uuid                                                     not null
        references formularios_formulario,
    index_version_id uuid                                                     not null
        references formularios_formularioindexversion,
    form_name        text                                                     not null,
    filled_at_local  timestamp with time zone                                 not null,
    status           varchar                  default 'pending'::entry_status not null,
    fill_json        jsonb                                                    not null
        constraint chk_fill_json_obj
            check (jsonb_typeof(fill_json) = 'object'::text),
    form_json        jsonb                                                    not null
        constraint chk_form_json_obj
            check (jsonb_typeof(form_json) = 'object'::text),
    created_at       timestamp with time zone default now()                   not null,
    updated_at       timestamp with time zone default now()                   not null
);

alter table formularios_entry
    owner to santa_ana;

create index if not exists idx_formularios_entry_form_version
    on formularios_entry (form_id, index_version_id);

create index if not exists idx_formularios_entry_filljson_gin
    on formularios_entry using gin (fill_json);

create index if not exists idx_formularios_entry_formjson_gin
    on formularios_entry using gin (form_json);

create index if not exists idx_formularios_entry_user_status
    on formularios_entry (id_usuario_id, status);

